/** The provider contract lives in the publishing-core package; re-exported for existing imports. */
export type {
  AccountType,
  LoadedMedia,
  MetricsInput,
  MetricsResult,
  PostMetrics,
  ProviderCapabilities,
  ProviderContext,
  ProviderCredentials,
  ProviderId,
  ProviderPostRef,
  PublishInput,
  PublishResult,
  PublishingProvider,
  RenderedContent,
  RenderedMedia,
  RetryableErrorCode,
  SocialAccountRef,
  TerminalErrorCode,
  ValidationIssue,
  ValidationResult,
} from '@postelyo/publishing-core';
